name: Build and Deploy Pokedex
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with: 
            persist-credentials: false

    - name: Instalacion y Build
      run: |
        npm install
        npm run build
        
    
    - name: Deploy en Github Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

    - name: Pruebas de acceso al sitio
      uses: ./load-test-action

